# Generated by Django 5.0.6 on 2024-06-18 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='orders',
        ),
    ]
